from docx import Document

def create_table(data, num_cols, num_rows, document):

    table = document.add_table(rows=num_rows, cols=num_cols)

    table.style = "Table Grid"

    # Merge cells in rows 3, 4, 5, and 6
    for i in range(2, 6):
        start_cell = table.cell(i, 1)
        end_cell = table.cell(i, 3)
        start_cell.merge(end_cell)

    cell_index = 0
    for row in table.rows:
        for cell in row.cells:
            if cell_index < len(data):
                cell.text = data[cell_index]
            cell_index += 1

    document.add_page_break() 

    return document

# Given text
texts = [['HU:', '1', 'Título:', 'Autenticación con Credenciales Universitarias  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero crear una cuenta personal e iniciar sesión de forma segura en el chatbot con mis credenciales universitarias, garantizando mi privacidad y la seguridad de mis datos.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Creación de cuenta Dado que soy un estudiante nuevo Cuando ingreso mis credenciales universitarias y detalles personales Entonces se crea exitosamente una cuenta personal asociada a mis datos.  \nEscenario 2: Inicio de sesión seguro Dado que tengo una cuenta registrada en el chatbot Cuando ingreso mis credenciales universitarias correctamente Entonces accedo de manera segura al sistema, protegiendo la privacidad y seguridad de mis datos.  ', 'Prioridad', '', '', 'Alta  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '2', 'Título:', 'Recuerdo de Sesiones y Conversaciones  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot recuerde mis sesiones y conversaciones anteriores, para poder reanudar las discusiones sin problemas y realizar un seguimiento de mi progreso a lo largo del tiempo.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Reanudar conversación anterior Dado que he tenido una conversación previa con el chatbot Cuando inicio una nueva sesión Entonces el chatbot recuerda la conversación anterior y puede continuarla de manera coherente.  \nEscenario 2: Seguimiento de progreso Dado que he tenido múltiples interacciones con el chatbot en diferentes sesiones Cuando accedo a un registro de progreso Entonces puedo ver un resumen de mis conversaciones anteriores y el progreso que he logrado a lo largo del tiempo.  ', 'Prioridad', '', '', 'Media ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '3', 'Título:', 'Denuncia de Contenido Inadecuado  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero poder denunciar cualquier tipo de contenido o recomendación inadecuada que brinde el chatbot, de forma que los desarrolladores puedan mejorar la funcionalidad y alcance del modelo.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Denuncia de contenido Dado que encuentro contenido inapropiado o inadecuado en la conversación Cuando uso la opción de denuncia proporcionada Entonces el sistema registra mi denuncia y los desarrolladores son notificados para abordar el problema.  \nEscenario 2: Retroalimentación sobre denuncias Dado que he realizado una denuncia en el pasado Cuando los desarrolladores toman medidas para abordar la denuncia Entonces recibo retroalimentación sobre las acciones tomadas para resolver el problema.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '4', 'Título:', 'Gestión de Acceso a Datos Personales  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero poder gestionar el nivel de acceso que se tenga a mis datos personales y conversaciones con el chatbot, para proteger mi integridad.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Configuración de privacidad Dado que quiero controlar quién accede a mis datos Cuando ajusto las preferencias de privacidad en mi perfil Entonces puedo especificar qué información es visible y quién puede acceder a mis conversaciones.  \nEscenario 2: Cambios en la configuración de privacidad Dado que mis necesidades de privacidad pueden cambiar con el tiempo Cuando modifico mis preferencias de privacidad en cualquier momento Entonces los cambios se aplican de manera efectiva y se respeta mi configuración actualizada.  ', 'Prioridad', '', '', 'Alta  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '5', 'Título:', 'Borrado de Historial y Datos  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot respete mi privacidad al brindar la opción de borrar mi historial de chat y mis datos, asegurándome de que mi información personal esté segura.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Borrado de historial Dado que deseo borrar el historial de mis conversaciones Cuando utilizo la opción de borrado de historial en mi perfil Entonces el chatbot elimina de manera permanente todas mis conversaciones anteriores.  \nEscenario 2: Borrado de datos personales Dado que quiero eliminar mis datos personales almacenados Cuando solicito el borrado de mis datos en mi perfil Entonces el chatbot procede a eliminar todos los datos personales relacionados con mi cuenta.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '6', 'Título:', 'Diseño de Interfaz Intuitiva  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que la interfaz del chatbot tenga un diseño limpio e intuitivo, que facilite la navegación y encuentre la ayuda que necesito para controlar mi ansiedad.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Navegación sencilla Dado que quiero acceder a diferentes secciones del chatbot Cuando utilizo la interfaz y las opciones de navegación Entonces encuentro de manera fácil y rápida la información que necesito.  \nEscenario 2: Diseño atractivo Dado que valoro una experiencia visual agradable Cuando interactúo con la interfaz del chatbot Entonces encuentro el diseño atractivo y coherente en todo momento.  ', 'Prioridad', '', '', 'Alta  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '7', 'Título:', 'Opciones de Comunicación Variadas  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot ofrezca múltiples opciones de comunicación, como texto, voz y emojis, que me permitan interactuar de la manera que me resulte más cómoda.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Comunicación por voz Dado que prefiero utilizar la voz para interactuar Cuando selecciono la opción de comunicación por voz Entonces el chatbot reconoce mi voz y responde de manera adecuada.  \nEscenario 2: Uso de emojis Dado que quiero expresar emociones a través de emojis Cuando utilizo emojis en mis conversaciones con el chatbot Entonces el chatbot comprende y responde de acuerdo a los emojis utilizados.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '8', 'Título:', 'Personalización de Perfil  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot brinde una opción para personalizar mi perfil con una imagen y un nombre preferido, creando una experiencia más personalizada y acogedora.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Cambio de imagen de perfil Dado que quiero agregar mi toque personal al perfil Cuando selecciono la opción para cambiar mi imagen de perfil Entonces puedo cargar una imagen y esta se muestra en mi perfil.  \nEscenario 2: Elección de nombre preferido Dado que prefiero que el chatbot me llame por un nombre específico Cuando establezco un nombre preferido en mi perfil Entonces el chatbot me dirige por ese nombre en las conversaciones.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '9', 'Título:', 'Sección de Ayuda y Solución de Problemas  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot tenga una sección de "Ayuda" con preguntas frecuentes y sugerencias para la solución de problemas, asegurándome de poder resolver cualquier problema técnico que encuentre mientras uso la plataforma.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Acceso a la sección de ayuda Dado que necesito asistencia o información adicional Cuando accedo a la sección de "Ayuda" desde el menú Entonces encuentro una lista de preguntas frecuentes y recursos para solucionar problemas.  \nEscenario 2: Resolución de problemas Dado que enfrento un problema técnico o de uso Cuando sigo las sugerencias y pasos proporcionados en la sección de ayuda Entonces encuentro una solución efectiva para mi problema.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '10', 'Título:', 'Guardar y Marcar Recursos Útiles  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot me permita guardar y marcar recursos útiles y técnicas de afrontamiento, para poder acceder a ellos fácilmente para consultarlos más adelante.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Guardar recurso Dado que encuentro un recurso útil o técnica de afrontamiento Cuando uso la opción de guardar en la conversación Entonces el recurso se almacena en una sección de marcadores para su acceso posterior.  \nEscenario 2: Acceso a recursos guardados Dado que deseo acceder a los recursos guardados Cuando navego a la sección de marcadores en el chatbot Entonces encuentro una lista de los recursos que he guardado y puedo acceder a ellos.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '11', 'Título:', 'Temas de Diseño Claros y Oscuros  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot ofrezca una opción para cambiar entre temas claros y oscuros, atendiendo a mis preferencias visuales y reduciendo la fatiga visual durante el uso nocturno.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Cambio de tema a oscuro Dado que prefiero un tema oscuro para reducir el brillo Cuando selecciono la opción de tema oscuro en la configuración Entonces el chatbot cambia su interfaz a colores oscuros y más suaves.  \nEscenario 2: Cambio de tema a claro Dado que prefiero un tema claro para una mayor visibilidad Cuando selecciono la opción de tema claro en la configuración Entonces el chatbot cambia su interfaz a colores claros y legibles.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '12', 'Título:', 'Iniciar Conversación para Controlar la Ansiedad  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero poder iniciar una conversación con el chatbot, para poder buscar ayuda para controlar mi ansiedad cuando la necesite.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Inicio de conversación Dado que siento ansiedad y necesito apoyo Cuando inicio una conversación con el chatbot Entonces el chatbot me brinda orientación y técnicas para manejar mi ansiedad en ese momento.  \nEscenario 2: Acceso rápido para iniciar conversación Dado que quiero un acceso rápido a la conversación Cuando utilizo un comando o botón específico para iniciar una conversación de ayuda Entonces el chatbot responde rápidamente y ofrece asistencia.  ', 'Prioridad', '', '', 'Alta  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '13', 'Título:', 'Técnicas de Relajación y Atención Plena  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot me proporcione técnicas de relajación y ejercicios de atención plena para poder reducir mis niveles de ansiedad durante los momentos estresantes.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Sugerencia de técnicas de relajación Dado que estoy buscando técnicas para reducir la ansiedad Cuando pido al chatbot que me sugiera técnicas de relajación Entonces el chatbot proporciona una variedad de técnicas efectivas.  \nEscenario 2: Ejercicios de atención plena Dado que deseo mejorar mi atención y reducir la ansiedad Cuando solicito ejercicios de atención plena al chatbot Entonces el chatbot guía a través de ejercicios para mantener la calma y reducir la ansiedad.  ', 'Prioridad', '', '', 'Alta  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '14', 'Título:', 'Equilibrio Trabajo-Vida Personal  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot ofrezca consejos para mantener un equilibrio saludable entre el trabajo y la vida personal, de modo que pueda administrar mejor mis compromisos académicos y mi bienestar personal.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Consejos para el equilibrio Dado que quiero lograr un balance entre mis responsabilidades Cuando solicito consejos para mantener un equilibrio saludable Entonces el chatbot ofrece recomendaciones prácticas para gestionar mi tiempo y prioridades.  \nEscenario 2: Consejos específicos para estudiantes Dado que necesito consejos relevantes para mi situación Cuando solicito consejos específicos para estudiantes en el manejo del tiempo Entonces el chatbot proporciona orientación adecuada a mis circunstancias académicas.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '15', 'Título:', 'Rutinas y Actividades de Autocuidado  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot me sugiera rutinas y actividades de autocuidado, para poder incorporarlas a mi rutina diaria para mejorar mi salud mental.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Sugerencias de rutinas de autocuidado Dado que deseo incorporar hábitos de bienestar a mi rutina Cuando pido al chatbot que me sugiera rutinas de autocuidado Entonces el chatbot ofrece ideas de actividades que promueven la salud mental.  \nEscenario 2: Incorporación a la rutina diaria Dado que quiero hacer del autocuidado una parte regular de mi vida Cuando el chatbot sugiere actividades prácticas y alcanzables Entonces puedo integrarlas fácilmente en mi rutina diaria.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '16', 'Título:', 'Compartir Historias de Éxito  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot comparta historias de éxito de otros estudiantes que han superado la ansiedad, para que pueda sentirme inspirado y motivado para trabajar en mi propia salud mental.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Acceso a historias de éxito Dado que busco inspiración y motivación Cuando solicito al chatbot que comparta historias de éxito de otros estudiantes Entonces el chatbot presenta relatos reales de superación y mejora en la salud mental.  \nEscenario 2: Mensajes motivadores Dado que necesito un impulso emocional positivo Cuando el chatbot comparte mensajes de ánimo y empoderamiento junto con las historias de éxito Entonces me siento inspirado y motivado para abordar mi propia salud mental.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '17', 'Título:', 'Información de Asesoramiento en el Campus  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot proporcione información sobre los servicios de asesoramiento disponibles en el campus, para poder acceder a ayuda profesional cuando sea necesario.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Acceso a información de asesoramiento Dado que busco ayuda profesional para mi salud mental Cuando solicito información sobre los servicios de asesoramiento en el campus Entonces el chatbot presenta detalles sobre cómo acceder a la ayuda disponible.  \nEscenario 2: Información actualizada Dado que la disponibilidad puede cambiar con el tiempo Cuando el chatbot comparte información actualizada y precisa sobre los servicios de asesoramiento Entonces me siento informado y capaz de buscar el apoyo necesario.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '18', 'Título:', 'Estrategias para Exámenes y Estrés  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot me recomiende estrategias para lidiar con el estrés relacionado con los exámenes y la ansiedad por el rendimiento, para que pueda tener un mejor rendimiento académico.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Estrategias de manejo del estrés en los exámenes Dado que enfrento ansiedad por los exámenes y el rendimiento Cuando solicito al chatbot estrategias para lidiar con el estrés Entonces el chatbot proporciona técnicas específicas para afrontar la ansiedad antes y durante los exámenes.  \nEscenario 2: Consejos para el rendimiento académico Dado que busco mejorar mi desempeño académico Cuando el chatbot brinda consejos para abordar la ansiedad relacionada con el rendimiento Entonces encuentro orientación útil para mantener un enfoque saludable y efectivo en los estudios.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '19', 'Título:', 'Estrategias para Ansiedad Social  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot sugiera técnicas para manejar la ansiedad social en entornos sociales y académicos, para que pueda relacionarme más cómodamente con compañeros y profesores.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Estrategias para enfrentar la ansiedad social Dado que enfrento ansiedad en situaciones sociales y académicas Cuando busco técnicas para manejar la ansiedad social Entonces el chatbot proporciona enfoques efectivos para reducir la ansiedad y mejorar la confianza en sí mismo.  \nEscenario 2: Sugerencias para interactuar con confianza Dado que deseo mejorar mis habilidades sociales Cuando el chatbot ofrece consejos prácticos para interactuar cómodamente con compañeros y profesores Entonces encuentro orientación útil para superar desafíos de ansiedad social.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '20', 'Título:', 'Ejercicios de Respiración e Imágenes Guiadas  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot ofrezca ejercicios de respiración e imágenes guiadas para ayudarme a mantener la calma durante situaciones que me provocan ansiedad.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Ejercicios de respiración Dado que busco técnicas para reducir la ansiedad en el momento Cuando solicito al chatbot ejercicios de respiración Entonces el chatbot guía a través de ejercicios de respiración que promueven la calma y el enfoque.  \nEscenario 2: Imágenes guiadas Dado que deseo técnicas visuales para reducir la ansiedad Cuando el chatbot proporciona imágenes guiadas para visualizar situaciones relajantes Entonces puedo usar estas técnicas para tranquilizarme durante momentos de ansiedad.  ', 'Prioridad', '', '', 'Alta  ', 'Tiempo Estimado', '', '', 'x'], ['HU:', '21', 'Título:', 'Estrategias de Afrontamiento Personalizadas  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot brinde sugerencias para estrategias de afrontamiento basadas en mis preferencias e intereses, para que pueda encontrar enfoques que resuenen conmigo.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Sugerencias personalizadas Dado que busco abordar la ansiedad de manera personalizada Cuando el chatbot considera mis preferencias e intereses al sugerir estrategias de afrontamiento Entonces recibo enfoques que se adaptan a mi estilo de vida y personalidad.  \nEscenario 2: Ajuste a las preferencias cambiantes Dado que mis necesidades pueden evolucionar con el tiempo Cuando ajusto mis preferencias y necesidades en el perfil Entonces el chatbot adapta las sugerencias de afrontamiento de acuerdo a mis cambios.  ', 'Prioridad', '', '', 'Alta  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '22', 'Título:', 'Consejos para Mejorar el Sueño  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot brinde sugerencias para mejorar la calidad del sueño, ya que el sueño adecuado es importante para controlar la ansiedad.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Sugerencias para el sueño Dado que busco mejorar mi calidad de sueño Cuando solicito al chatbot consejos para un mejor descanso Entonces el chatbot ofrece recomendaciones prácticas para mejorar mis hábitos de sueño.  \nEscenario 2: Estrategias para el insomnio Dado que enfrento dificultades para conciliar el sueño Cuando el chatbot proporciona estrategias para superar el insomnio Entonces encuentro orientación para abordar los problemas de sueño y reducir la ansiedad asociada.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x'],
['HU:', '23', 'Título:', 'Comunicación con Profesores sobre Ansiedad  ', 'Usuario:', 'Estudiante  ', 'Sprint:', 'x  ', 'Descripción', '', '', 'Como estudiante, quiero que el chatbot ofrezca consejos para una comunicación efectiva con los profesores sobre mi ansiedad y posibles adaptaciones, para que pueda manejar mejor mis responsabilidades académicas.  ', 'Criterios de Aceptación', '', '', 'Escenario 1: Consejos para comunicar la ansiedad Dado que busco expresar mi ansiedad a los profesores Cuando solicito al chatbot consejos para comunicarme de manera efectiva Entonces el chatbot brinda recomendaciones para hablar con claridad y obtener apoyo.  \nEscenario 2: Adaptaciones académicas Dado que necesito adaptaciones en mi entorno académico Cuando el chatbot sugiere estrategias para solicitar adaptaciones a los profesores Entonces encuentro orientación para asegurar que mis necesidades sean comprendidas y atendidas.  ', 'Prioridad', '', '', 'Media  ', 'Tiempo Estimado', '', '', 'x']]




# Define the number of columns and rows
num_cols = 4
num_rows = 6

# Create the Word document and save it
#document = create_table(text, num_cols, num_rows)
#document.save("table.docx")

document = Document()

for text in texts:
    document = create_table(text, num_cols, num_rows, document)

document.save("table.docx")